package gui;

public enum DialogType {
	ADD_VACANCY, REMOVE_VACANCY, ADD_ORGANISATION, REMOVE_ORGANISATION, ADD_CANDIDATE, REMOVE_CANDIDATE, ADD_CONTACT, REMOVE_CONTACT, CANDIDATE_ADD_LINKEDIN, 
	ADD_CANDIDATE_SKILL, REMOVE_CANDIDATE_SKILL, ADD_EVENT, REMOVE_EVENT, ADD_TASK, ADD_USER, REMOVE_USER, EDIT_USER, ADD_SKILL;
}
